FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY backend/go.mod backend/go.sum ./
RUN go mod download

COPY backend ./
COPY frontend ../frontend

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /siem-backend ./cmd/server/main.go

FROM alpine:3.18

RUN adduser -D siemuser

WORKDIR /home/siemuser/

COPY --from=builder /siem-backend .
COPY --from=builder /frontend ./frontend

USER siemuser

EXPOSE 8080

CMD ["./siem-backend"]