FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /nosql-server ./cmd/server/main.go

FROM alpine:3.19

RUN adduser -D dbuser
USER dbuser

WORKDIR /home/dbuser

COPY --from=builder /nosql-server .

RUN mkdir -p ./data

COPY --from=builder /app/data/security_events.json ./data/

EXPOSE 5140

CMD ["./nosql-server"]